In [4]:
import numpy as np
import pandas as pd

In this file I will be merging US Population data taken from the US census website into one single data frame. This data fram will contain the populations in all states, by county for 2006-2012. We have to merge two separate data files, one with pre-2010 information and one with post-2010 information.

In [5]:
Census20102012 = pd.read_csv("https://raw.githubusercontent.com/MIDS-at-Duke/pds2021-opioids-team-three/censusdata/co-est2012-alldata.csv?token=AVVHZRTDDEETHC274H3LHL3BQ3B6O", encoding="ISO-8859-1")
Census20102012.sample(5)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDEATH2011,RDEATH2012,RNATURALINC2011,RNATURALINC2012,RINTERNATIONALMIG2011,RINTERNATIONALMIG2012,RDOMESTICMIG2011,RDOMESTICMIG2012,RNETMIG2011,RNETMIG2012
748,50,2,3,18,73,Indiana,Jasper County,33478,33478,33531,...,9.439176,9.330144,2.120827,1.854067,-0.059742,-0.029904,-5.466358,-0.747608,-5.526100,-0.777512
1172,50,3,7,22,81,Louisiana,Red River Parish,9091,9091,9034,...,9.416196,12.109093,5.206602,0.999833,0.000000,0.000000,-6.314390,-5.221352,-6.314390,-5.221352
177,50,3,7,5,125,Arkansas,Saline County,107118,107118,107662,...,8.370008,8.085998,3.528082,3.155072,1.212778,1.271043,15.104602,11.854055,16.317380,13.125099
1703,50,2,4,31,43,Nebraska,Dakota County,21006,21006,21038,...,7.057197,6.264496,11.682522,11.668221,3.385547,3.921287,-21.934530,-15.206944,-18.548983,-11.285656
515,50,3,5,13,239,Georgia,Quitman County,2513,2513,2506,...,7.669021,8.242324,2.421796,3.709046,0.000000,0.000000,-25.428860,-22.254276,-25.428860,-22.254276

In [6]:
for col in Census20102012.columns:
        print(col)

SUMLEV
REGION
DIVISION
STATE
COUNTY
STNAME
CTYNAME
CENSUS2010POP
ESTIMATESBASE2010
POPESTIMATE2010
POPESTIMATE2011
POPESTIMATE2012
NPOPCHG_2010
NPOPCHG_2011
NPOPCHG_2012
BIRTHS2010
BIRTHS2011
BIRTHS2012
DEATHS2010
DEATHS2011
DEATHS2012
NATURALINC2010
NATURALINC2011
NATURALINC2012
INTERNATIONALMIG2010
INTERNATIONALMIG2011
INTERNATIONALMIG2012
DOMESTICMIG2010
DOMESTICMIG2011
DOMESTICMIG2012
NETMIG2010
NETMIG2011
NETMIG2012
RESIDUAL2010
RESIDUAL2011
RESIDUAL2012
GQESTIMATESBASE2010
GQESTIMATES2010
GQESTIMATES2011
GQESTIMATES2012
RBIRTH2011
RBIRTH2012
RDEATH2011
RDEATH2012
RNATURALINC2011
RNATURALINC2012
RINTERNATIONALMIG2011
RINTERNATIONALMIG2012
RDOMESTICMIG2011
RDOMESTICMIG2012
RNETMIG2011
RNETMIG2012

From this, we know that the relevant columns to keep are:
REGION
DIVISION
STNAME
CTYNAME
CENSUS2010POP
POPESTIMATE2011
POPESTIMATE2012

In [7]:
Census20102012sub = Census20102012[['STNAME', 'CTYNAME', 'CENSUS2010POP', 'POPESTIMATE2011', 'POPESTIMATE2012']]
Census20102012sub

,STNAME,CTYNAME,CENSUS2010POP,POPESTIMATE2011,POPESTIMATE2012
0,Alabama,Alabama,4779736,4803689,4822023
1,Alabama,Autauga County,54571,55392,55514
2,Alabama,Baldwin County,182265,186830,190790
3,Alabama,Barbour County,27457,27313,27201
4,Alabama,Bibb County,22915,22738,22597
...,...,...,...,...,...
3189,Wyoming,Sweetwater County,43806,44078,45267
3190,Wyoming,Teton County,21294,21445,21675
3191,Wyoming,Uinta County,21118,20919,21025
3192,Wyoming,Washakie County,8533,8469,8464
3193,Wyoming,Weston County,7208,7109,7082

In [8]:
Census20102012sub.rename({'STNAME': 'STATE', 'CTYNAME': 'COUNTY', 'CENSUS2010POP': 'POP2010', 'POPESTIMATE2011': 'POP2011', 'POPESTIMATE2012': 'POP2012'}, axis=1, inplace=True)

Census20102012sub

/Users/hmeikle2016/opt/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py:5034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

        STATE             COUNTY  POP2010  POP2011  POP2012
0     Alabama            Alabama  4779736  4803689  4822023
1     Alabama     Autauga County    54571    55392    55514
2     Alabama     Baldwin County   182265   186830   190790
3     Alabama     Barbour County    27457    27313    27201
4     Alabama        Bibb County    22915    22738    22597
...       ...                ...      ...      ...      ...
3189  Wyoming  Sweetwater County    43806    44078    45267
3190  Wyoming       Teton County    21294    21445    21675
3191  Wyoming       Uinta County    21118    20919    21025
3192  Wyoming    Washakie County     8533     8469     8464
3193  Wyoming      Weston County     7208     7109     7082

[3194 rows x 5 columns]

In [9]:
Census20002009 = pd.read_csv("https://raw.githubusercontent.com/MIDS-at-Duke/pds2021-opioids-team-three/censusdata/co-est2009-alldata.csv?token=AVVHZRR2FXMPMLPCSA3DJT3BQ3BV2", encoding="ISO-8859-1")
Census20002009.sample(5)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2000POP,ESTIMATESBASE2000,POPESTIMATE2000,...,RDOMESTICMIG2009,RNETMIG2001,RNETMIG2002,RNETMIG2003,RNETMIG2004,RNETMIG2005,RNETMIG2006,RNETMIG2007,RNETMIG2008,RNETMIG2009
1236,50,3,5,24,47,Maryland,Worcester County,46543,46543,46772,...,-0.122086,18.989086,15.531224,12.051922,7.806817,0.020465,7.375249,5.148136,0.325236,1.098778
119,50,3,7,5,9,Arkansas,Boone County,33948,33948,34051,...,-1.900005,6.236824,4.455121,3.017160,9.517218,15.743996,15.581431,17.049523,3.890310,-1.411433
293,50,4,8,8,85,Colorado,Montrose County,33432,33432,33600,...,16.679691,18.398045,18.430526,14.099630,11.716250,19.246257,24.132931,30.818827,20.716573,17.461170
3025,50,4,9,53,47,Washington,Okanogan County,39564,39564,39554,...,3.198334,-14.541572,-9.080881,-8.762180,4.397367,3.134394,0.102205,3.730633,8.556660,6.371874
566,50,4,8,16,5,Idaho,Bannock County,75565,75565,75671,...,3.284373,-5.158360,-9.875517,-15.193477,-6.739073,-7.092380,1.416574,-2.704598,2.006552,3.955899

Same format as previous file so we can use same format except we are using Pop. estimates from 2006-2009

In [10]:
Census20002009sub = Census20002009[['STNAME', 'CTYNAME', 'POPESTIMATE2006', 'POPESTIMATE2007','POPESTIMATE2008', 'POPESTIMATE2009']]
Census20002009sub

,STNAME,CTYNAME,POPESTIMATE2006,POPESTIMATE2007,POPESTIMATE2008,POPESTIMATE2009
0,Alabama,Alabama,4597688,4637904,4677464,4708708
1,Alabama,Autauga County,49105,49834,50354,50756
2,Alabama,Baldwin County,168516,172815,176212,179878
3,Alabama,Barbour County,29556,29736,29836,29737
4,Alabama,Bibb County,21285,21485,21589,21587
...,...,...,...,...,...,...
3189,Wyoming,Sweetwater County,37948,39320,39942,41226
3190,Wyoming,Teton County,19666,20073,20541,20710
3191,Wyoming,Uinta County,19631,20071,20537,20927
3192,Wyoming,Washakie County,7671,7805,7807,7911
3193,Wyoming,Weston County,6568,6845,6928,7009

In [11]:
Census20002009sub.rename({'STNAME': 'STATE', 'CTYNAME': 'COUNTY', 'POPESTIMATE2006': 'POP2006', 'POPESTIMATE2007': 'POP2007', 'POPESTIMATE2008': 'POP2008','POPESTIMATE2009': 'POP2009'}, axis=1, inplace=True)

Census20002009sub

/Users/hmeikle2016/opt/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py:5034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

        STATE             COUNTY  POP2006  POP2007  POP2008  POP2009
0     Alabama            Alabama  4597688  4637904  4677464  4708708
1     Alabama     Autauga County    49105    49834    50354    50756
2     Alabama     Baldwin County   168516   172815   176212   179878
3     Alabama     Barbour County    29556    29736    29836    29737
4     Alabama        Bibb County    21285    21485    21589    21587
...       ...                ...      ...      ...      ...      ...
3189  Wyoming  Sweetwater County    37948    39320    39942    41226
3190  Wyoming       Teton County    19666    20073    20541    20710
3191  Wyoming       Uinta County    19631    20071    20537    20927
3192  Wyoming    Washakie County     7671     7805     7807     7911
3193  Wyoming      Weston County     6568     6845     6928     7009

[3194 rows x 6 columns]

In [12]:
Check = (Census20002009sub['STATE'] == Census20002009sub['COUNTY'])
Check.value_counts()

False    3142
True       52
dtype: int64

Noticed that the total state populations are ALSO included so I will want to drop those from final clean data

There are different spellings of LaSalle Parish in LA in the two data sets I am working with so I need to change the name in my 2000-2009 data set to match with my second dataset.

In [13]:
Census20002009sub.loc[Census20002009sub.COUNTY == "La Salle Parish", "COUNTY"] = 'LaSalle Parish'

/Users/hmeikle2016/opt/miniconda3/lib/python3.9/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [14]:
Population = pd.merge(Census20002009sub, Census20102012sub, on = ['STATE', 'COUNTY'], how = 'outer', indicator = True)

Population.sample(20)

,STATE,COUNTY,POP2006,POP2007,POP2008,POP2009,POP2010,POP2011,POP2012,_merge
1457,Mississippi,Jackson County,128190,130971,132010,132922,139668,140210,140298,both
432,Georgia,Cobb County,679699,691496,704822,714692,688078,697366,707442,both
3119,Wisconsin,Fond du Lac County,98910,99376,99864,100070,101633,101856,101843,both
2745,Texas,Nolan County,14590,14580,14909,14917,15216,15145,14924,both
2545,Tennessee,Roane County,53084,53309,53473,53508,54181,53799,53469,both
1490,Mississippi,Sharkey County,5752,5489,5492,5420,4916,4889,4799,both
2798,Texas,Upshur County,37328,37515,37882,38057,39309,39784,39995,both
2643,Texas,Fayette County,22472,22566,22805,22891,24554,24755,24695,both
1150,Louisiana,East Baton Rouge Parish,430886,430700,431024,434633,440171,441602,444526,both
1735,Nebraska,Keya Paha County,877,841,821,802,824,826,804,both
639,Illinois,Fulton County,36984,36831,36714,36652,37069,36935,36651,both
1739,Nebraska,Lincoln County,35464,35448,35672,35670,36288,36112,36099,both
2649,Texas,Freestone County,18811,18820,19077,19390,19816,19632,19515,both
1467,Mississippi,Leake County,22622,22763,22970,23132,23805,23310,23297,both
2884,Virginia,Campbell County,52411,52529,52874,52976,54842,55220,55163,both
2325,Pennsylvania,Lycoming County,117186,116838,116666,116840,116111,116678,117168,both
1068,Kentucky,Jefferson County,704755,711766,717414,721594,741096,746372,750828,both
1668,Montana,Richland County,9043,9099,9164,9313,9746,10143,10810,both
1677,Montana,Toole County,5139,4989,5052,5151,5324,5167,5220,both
472,Georgia,Hart County,24129,24123,24252,24067,25213,25431,25518,both

In [15]:
Population[Population._merge != "both"]

Empty DataFrame
Columns: [STATE, COUNTY, POP2006, POP2007, POP2008, POP2009, POP2010, POP2011, POP2012, _merge]
Index: []

Data was merged so that it was the same on both sides (thanks to the changing of La Salle Parish to LaSalle Parish). Now to drop the state total populations.

In [16]:
CountyPopulations = Population[Population['COUNTY'] != Population["STATE"]]
CountyPopulations.sample(20)

,STATE,COUNTY,POP2006,POP2007,POP2008,POP2009,POP2010,POP2011,POP2012,_merge
1184,Louisiana,St. Mary Parish,51569,51163,51005,50815,54650,54234,53697,both
1197,Louisiana,Winn Parish,15680,15541,15385,15331,15313,15104,15000,both
2717,Texas,Live Oak County,11352,11293,11201,11046,11531,11531,11664,both
378,Florida,Okeechobee County,39813,40023,40222,40241,39996,39551,39467,both
581,Idaho,Cassia County,20747,20959,21447,21698,22952,23138,23249,both
2257,Oregon,Douglas County,103685,103688,103529,103205,107667,107400,107164,both
1392,Minnesota,Nobles County,20069,20090,20425,20558,21378,21446,21487,both
1610,Missouri,Scott County,40702,40825,40764,40855,39191,39115,39139,both
2299,Pennsylvania,Chester County,480200,487567,493281,498894,498886,503662,506575,both
3112,Wisconsin,Dane County,468750,476261,483298,491357,488073,496456,503523,both
2264,Oregon,Josephine County,80632,80693,81174,81026,82713,82680,82930,both
2670,Texas,Harrison County,63294,63299,63775,64795,65631,67302,67450,both
916,Kansas,Chautauqua County,3850,3775,3756,3745,3669,3621,3571,both
2906,Virginia,Grayson County,16149,16128,16003,15793,15533,15380,15183,both
786,Indiana,Shelby County,43715,43956,44223,44503,44436,44423,44471,both
1192,Louisiana,Washington Parish,44017,45059,45554,45669,47168,47125,46670,both
2835,Utah,Juab County,9132,9551,9999,10244,10246,10333,10341,both
1002,Kansas,Sumner County,24038,23757,23668,23488,24132,23835,23674,both
1827,New Jersey,Warren County,109450,109684,109897,109638,108692,108139,107653,both
839,Iowa,Fayette County,20701,20379,20238,20164,20880,20976,20793,both

Checking that the state population was actually dropped:

In [17]:
Check2 = (CountyPopulations['STATE'] == CountyPopulations['COUNTY'])
Check2.value_counts()

False    3142
dtype: int64