In [165]:
import numpy as np
import pandas as pd

In this file I will be merging US Population data taken from the US census website into one single data frame. This data fram will contain the populations in all states, by county for 2006-2012. We have to merge two separate data files, one with pre-2010 information and one with post-2010 information.

In [166]:
Census20102012 = pd.read_csv("https://raw.githubusercontent.com/MIDS-at-Duke/pds2021-opioids-team-three/censusdata/MidSemester/00_data/co-est2015-alldata-1.csv?token=AVVHZRVBT2T5NJYQ73KTJJLBRLTFG", encoding="ISO-8859-1")
Census20102012.sample(5)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1055,50,3,6,21,89,Kentucky,Greenup County,36910,36914,36900,...,0.054247,-1.713377,-4.919175,-2.857928,-5.720840,0.135617,-1.631787,-4.837189,-2.775488,-5.637929
1135,50,3,7,22,7,Louisiana,Assumption Parish,23421,23421,23352,...,-9.585832,-7.482699,2.335287,-9.696550,-9.245127,-9.456875,-7.223183,2.594763,-9.393533,-8.939863
1960,50,3,5,37,73,North Carolina,Gates County,12197,12186,12160,...,-7.346265,-14.761686,-17.311609,-11.375878,-5.743875,-7.181180,-14.594888,-17.141887,-11.203516,-5.569819
2952,50,3,5,51,179,Virginia,Stafford County,128961,128952,129844,...,7.973904,4.934735,9.107857,11.088611,2.347102,9.393182,8.549540,11.583780,13.745258,5.445843
886,50,2,4,19,163,Iowa,Scott County,165224,165224,165744,...,2.776426,4.834859,4.591144,-0.321684,-2.223755,3.593728,5.698226,5.551807,0.795438,-1.123520

In [167]:
for col in Census20102012.columns:
        print(col)

SUMLEV
REGION
DIVISION
STATE
COUNTY
STNAME
CTYNAME
CENSUS2010POP
ESTIMATESBASE2010
POPESTIMATE2010
POPESTIMATE2011
POPESTIMATE2012
POPESTIMATE2013
POPESTIMATE2014
POPESTIMATE2015
NPOPCHG_2010
NPOPCHG_2011
NPOPCHG_2012
NPOPCHG_2013
NPOPCHG_2014
NPOPCHG_2015
BIRTHS2010
BIRTHS2011
BIRTHS2012
BIRTHS2013
BIRTHS2014
BIRTHS2015
DEATHS2010
DEATHS2011
DEATHS2012
DEATHS2013
DEATHS2014
DEATHS2015
NATURALINC2010
NATURALINC2011
NATURALINC2012
NATURALINC2013
NATURALINC2014
NATURALINC2015
INTERNATIONALMIG2010
INTERNATIONALMIG2011
INTERNATIONALMIG2012
INTERNATIONALMIG2013
INTERNATIONALMIG2014
INTERNATIONALMIG2015
DOMESTICMIG2010
DOMESTICMIG2011
DOMESTICMIG2012
DOMESTICMIG2013
DOMESTICMIG2014
DOMESTICMIG2015
NETMIG2010
NETMIG2011
NETMIG2012
NETMIG2013
NETMIG2014
NETMIG2015
RESIDUAL2010
RESIDUAL2011
RESIDUAL2012
RESIDUAL2013
RESIDUAL2014
RESIDUAL2015
GQESTIMATESBASE2010
GQESTIMATES2010
GQESTIMATES2011
GQESTIMATES2012
GQESTIMATES2013
GQESTIMATES2014
GQESTIMATES2015
RBIRTH2011
RBIRTH2012
RBIRTH2013
RBIRTH2014
RBIRTH2015
RDEATH2011
RDEATH2012
RDEATH2013
RDEATH2014
RDEATH2015
RNATURALINC2011
RNATURALINC2012
RNATURALINC2013
RNATURALINC2014
RNATURALINC2015
RINTERNATIONALMIG2011
RINTERNATIONALMIG2012
RINTERNATIONALMIG2013
RINTERNATIONALMIG2014
RINTERNATIONALMIG2015
RDOMESTICMIG2011
RDOMESTICMIG2012
RDOMESTICMIG2013
RDOMESTICMIG2014
RDOMESTICMIG2015
RNETMIG2011
RNETMIG2012
RNETMIG2013
RNETMIG2014
RNETMIG2015

From this, we know that the relevant columns to keep are:
REGION
DIVISION
STNAME
CTYNAME
CENSUS2010POP
POPESTIMATE2011
POPESTIMATE2012

In [168]:
Census20102012sub = Census20102012[['STNAME', 'CTYNAME', 'CENSUS2010POP', 'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015']]
Census20102012sub

,STNAME,CTYNAME,CENSUS2010POP,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
0,Alabama,Alabama,4779736,4801108,4816089,4830533,4846411,4858979
1,Alabama,Autauga County,54571,55253,55175,55038,55290,55347
2,Alabama,Baldwin County,182265,186659,190396,195126,199713,203709
3,Alabama,Barbour County,27457,27226,27159,26973,26815,26489
4,Alabama,Bibb County,22915,22733,22642,22512,22549,22583
...,...,...,...,...,...,...,...,...
3188,Wyoming,Sweetwater County,43806,44041,45104,45162,44925,44626
3189,Wyoming,Teton County,21294,21482,21697,22347,22905,23125
3190,Wyoming,Uinta County,21118,20912,20989,21022,20903,20822
3191,Wyoming,Washakie County,8533,8469,8443,8443,8316,8328
3192,Wyoming,Weston County,7208,7114,7065,7160,7185,7234

In [169]:
Census20102012sub.rename({'STNAME': 'STATE', 'CTYNAME': 'COUNTY', 'CENSUS2010POP': '2010', 'POPESTIMATE2011': '2011', 'POPESTIMATE2012': '2012', 'POPESTIMATE2013': '2013', 'POPESTIMATE2014': '2014', 'POPESTIMATE2015': '2015'}, axis=1, inplace=True)

Census20102012sub

/Users/hmeikle2016/opt/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py:5034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,STATE,COUNTY,2010,2011,2012,2013,2014,2015
0,Alabama,Alabama,4779736,4801108,4816089,4830533,4846411,4858979
1,Alabama,Autauga County,54571,55253,55175,55038,55290,55347
2,Alabama,Baldwin County,182265,186659,190396,195126,199713,203709
3,Alabama,Barbour County,27457,27226,27159,26973,26815,26489
4,Alabama,Bibb County,22915,22733,22642,22512,22549,22583
...,...,...,...,...,...,...,...,...
3188,Wyoming,Sweetwater County,43806,44041,45104,45162,44925,44626
3189,Wyoming,Teton County,21294,21482,21697,22347,22905,23125
3190,Wyoming,Uinta County,21118,20912,20989,21022,20903,20822
3191,Wyoming,Washakie County,8533,8469,8443,8443,8316,8328
3192,Wyoming,Weston County,7208,7114,7065,7160,7185,7234

In [170]:
Census20002009 = pd.read_csv("https://raw.githubusercontent.com/MIDS-at-Duke/pds2021-opioids-team-three/censusdata/MidSemester/00_data/co-est2009-alldata.csv?token=AVVHZRXAAUHE3DNX32FWTELBRLTMG", encoding="ISO-8859-1")
Census20002009.sample(5)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2000POP,ESTIMATESBASE2000,POPESTIMATE2000,...,RDOMESTICMIG2009,RNETMIG2001,RNETMIG2002,RNETMIG2003,RNETMIG2004,RNETMIG2005,RNETMIG2006,RNETMIG2007,RNETMIG2008,RNETMIG2009
1626,50,4,8,30,3,Montana,Big Horn County,12671,12671,12659,...,2.478315,0.157085,-15.405067,-14.351253,-3.518924,-17.022606,-15.467965,-8.485896,-9.546166,2.942999
745,50,2,3,18,67,Indiana,Howard County,84964,84964,84969,...,-10.972766,-3.130793,-5.744516,-3.204863,-4.810370,-1.363941,-8.344279,-5.093460,-5.583720,-10.203591
55,50,3,6,1,109,Alabama,Pike County,29605,29693,29734,...,-1.380852,-6.805357,-13.240536,3.305391,7.879608,-2.928701,9.319477,3.557122,1.354096,-0.526039
144,50,3,7,5,59,Arkansas,Hot Spring County,30353,30353,30383,...,-4.804296,-0.527113,1.416431,2.105021,5.179394,11.954068,20.078652,7.440218,-0.345017,-4.584491
2507,50,3,6,47,73,Tennessee,Hawkins County,53563,53563,53689,...,5.223745,6.973552,6.221699,8.711772,6.468387,10.148364,9.918325,8.681335,6.830649,5.570837

Same format as previous file so we can use same format except we are using Pop. estimates from 2006-2009

In [171]:
Census20002009sub = Census20002009[['STNAME', 'CTYNAME', 'POPESTIMATE2006', 'POPESTIMATE2007','POPESTIMATE2008', 'POPESTIMATE2009']]
Census20002009sub

,STNAME,CTYNAME,POPESTIMATE2006,POPESTIMATE2007,POPESTIMATE2008,POPESTIMATE2009
0,Alabama,Alabama,4597688,4637904,4677464,4708708
1,Alabama,Autauga County,49105,49834,50354,50756
2,Alabama,Baldwin County,168516,172815,176212,179878
3,Alabama,Barbour County,29556,29736,29836,29737
4,Alabama,Bibb County,21285,21485,21589,21587
...,...,...,...,...,...,...
3189,Wyoming,Sweetwater County,37948,39320,39942,41226
3190,Wyoming,Teton County,19666,20073,20541,20710
3191,Wyoming,Uinta County,19631,20071,20537,20927
3192,Wyoming,Washakie County,7671,7805,7807,7911
3193,Wyoming,Weston County,6568,6845,6928,7009

In [172]:
Census20002009sub.rename({'STNAME': 'STATE', 'CTYNAME': 'COUNTY', 'POPESTIMATE2006': '2006', 'POPESTIMATE2007': '2007', 'POPESTIMATE2008': '2008','POPESTIMATE2009': '2009'}, axis=1, inplace=True)

Census20002009sub

/Users/hmeikle2016/opt/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py:5034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

        STATE             COUNTY     2006     2007     2008     2009
0     Alabama            Alabama  4597688  4637904  4677464  4708708
1     Alabama     Autauga County    49105    49834    50354    50756
2     Alabama     Baldwin County   168516   172815   176212   179878
3     Alabama     Barbour County    29556    29736    29836    29737
4     Alabama        Bibb County    21285    21485    21589    21587
...       ...                ...      ...      ...      ...      ...
3189  Wyoming  Sweetwater County    37948    39320    39942    41226
3190  Wyoming       Teton County    19666    20073    20541    20710
3191  Wyoming       Uinta County    19631    20071    20537    20927
3192  Wyoming    Washakie County     7671     7805     7807     7911
3193  Wyoming      Weston County     6568     6845     6928     7009

[3194 rows x 6 columns]

In [173]:
Check = (Census20002009sub['STATE'] == Census20002009sub['COUNTY'])
Check.value_counts()

False    3142
True       52
dtype: int64

Noticed that the total state populations are ALSO included so I will want to drop those from final clean data

Changing some of the county names for the data so that it will merge better (some county names were changed in the past few years)

In [174]:
Census20002009sub.loc[Census20002009sub.COUNTY == "La Salle Parish", "COUNTY"] = 'LaSalle Parish'
Census20002009sub.loc[Census20002009sub.COUNTY == "Petersburg Census Area", "COUNTY"] = 'Petersburg Borough'
Census20102012sub.loc[Census20102012sub.COUNTY == "Oglala Lakota County", "COUNTY"] = 'Shannon County'
Census20002009sub.loc[Census20002009sub.COUNTY == "Wade Hampton Census Area", "COUNTY"] = 'Kusilvak Census Area'
Census20002009sub.loc[Census20002009sub.COUNTY == "Wade Hampton Census Area", "COUNTY"] = 'Kusilvak Census Area'

/Users/hmeikle2016/opt/miniconda3/lib/python3.9/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [175]:
Population = pd.merge(Census20002009sub, Census20102012sub, on = ['STATE', 'COUNTY'], how = 'outer', indicator = True)

Population.sample(20)

,STATE,COUNTY,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,_merge
795,Indiana,Vanderburgh County,174161,174819,174786,175434,179703.0,180357.0,180854.0,181521.0,181918.0,181877.0,both
1710,Nebraska,Dodge County,35881,35857,35662,35640,36691.0,36946.0,36645.0,36605.0,36725.0,36706.0,both
445,Georgia,Dooly County,11702,11536,11517,11819,14918.0,14557.0,14343.0,14325.0,14203.0,14035.0,both
117,Arkansas,Baxter County,41155,41845,41946,42157,41513.0,41273.0,41066.0,40965.0,40842.0,41053.0,both
1350,Minnesota,Cass County,28722,28640,28707,28534,28567.0,28388.0,28419.0,28521.0,28559.0,28706.0,both
673,Illinois,Mason County,15129,15048,14965,14785,14666.0,14483.0,14343.0,14190.0,13914.0,13701.0,both
1089,Kentucky,Magoffin County,13110,13158,13051,13166,13333.0,13208.0,13023.0,12911.0,12946.0,12808.0,both
2494,Tennessee,Dickson County,46439,47411,47915,48230,49666.0,49934.0,50153.0,50195.0,50592.0,51487.0,both
2230,Oklahoma,Pittsburg County,44249,44423,44776,45211,45837.0,45628.0,45107.0,44842.0,44619.0,44610.0,both
442,Georgia,Decatur County,28377,28543,28754,28838,27842.0,27652.0,27455.0,27369.0,27239.0,27174.0,both
2909,Virginia,Halifax County,35598,35428,35370,35258,36241.0,36010.0,35786.0,35388.0,35223.0,35125.0,both
302,Colorado,Rio Blanco County,6033,6198,6318,6534,6666.0,6778.0,6790.0,6742.0,6681.0,6571.0,both
2148,Ohio,Preble County,41833,41651,41651,41422,42270.0,42007.0,41856.0,41697.0,41521.0,41329.0,both
2196,Oklahoma,Grant County,4513,4482,4448,4317,4527.0,4546.0,4508.0,4514.0,4496.0,4523.0,both
317,Connecticut,Litchfield County,188393,188465,188647,188728,189927.0,188945.0,187455.0,186609.0,184910.0,183603.0,both
2912,Virginia,Henry County,55687,55594,55392,54888,54151.0,53330.0,52907.0,52631.0,52153.0,51881.0,both
2731,Texas,Medina County,43199,43749,44228,44728,46006.0,46517.0,46830.0,47319.0,47876.0,48417.0,both
2511,Tennessee,Henderson County,26523,26759,26981,27037,27769.0,28032.0,28025.0,27976.0,28017.0,28015.0,both
2960,Virginia,Westmoreland County,17018,17332,17564,17686,17454.0,17626.0,17512.0,17557.0,17462.0,17629.0,both
97,Alaska,Yukon-Koyukuk Census Area,5845,5811,5712,5627,5588.0,5731.0,5731.0,5661.0,5563.0,5533.0,both

In [176]:
Population[Population._merge != "both"]

,STATE,COUNTY,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,_merge
2965,Virginia,Bedford city,6243,6292,6315,6350,NaN,NaN,NaN,NaN,NaN,NaN,left_only

Only one unmatched column so will just drop it.

In [177]:
Population.dropna

<bound method DataFrame.dropna of         STATE             COUNTY     2006     2007     2008     2009  \
0     Alabama            Alabama  4597688  4637904  4677464  4708708
1     Alabama     Autauga County    49105    49834    50354    50756
2     Alabama     Baldwin County   168516   172815   176212   179878
3     Alabama     Barbour County    29556    29736    29836    29737
4     Alabama        Bibb County    21285    21485    21589    21587
...       ...                ...      ...      ...      ...      ...
3191  Wyoming  Sweetwater County    37948    39320    39942    41226
3192  Wyoming       Teton County    19666    20073    20541    20710
3193  Wyoming       Uinta County    19631    20071    20537    20927
3194  Wyoming    Washakie County     7671     7805     7807     7911
3195  Wyoming      Weston County     6568     6845     6928     7009

           2010       2011       2012       2013       2014       2015 _merge
0     4779736.0  4801108.0  4816089.0  4830533.0  4846411.0  4858979.0   both
1       54571.0    55253.0    55175.0    55038.0    55290.0    55347.0   both
2      182265.0   186659.0   190396.0   195126.0   199713.0   203709.0   both
3       27457.0    27226.0    27159.0    26973.0    26815.0    26489.0   both
4       22915.0    22733.0    22642.0    22512.0    22549.0    22583.0   both
...         ...        ...        ...        ...        ...        ...    ...
3191    43806.0    44041.0    45104.0    45162.0    44925.0    44626.0   both
3192    21294.0    21482.0    21697.0    22347.0    22905.0    23125.0   both
3193    21118.0    20912.0    20989.0    21022.0    20903.0    20822.0   both
3194     8533.0     8469.0     8443.0     8443.0     8316.0     8328.0   both
3195     7208.0     7114.0     7065.0     7160.0     7185.0     7234.0   both

[3196 rows x 13 columns]>

Data was merged so that it was the same on both sides (thanks to the changing of La Salle Parish to LaSalle Parish). Now to drop the state total populations.

In [178]:
CountyPopulations = Population[Population['COUNTY'] != Population["STATE"]]
CountyPopulations.sample(20)

,STATE,COUNTY,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,_merge
1288,Michigan,Ingham County,279261,278624,277971,277633,280895.0,282037.0,282386.0,282684.0,284263.0,286085.0,both
142,Arkansas,Greene County,39907,40302,40618,40996,42090.0,42733.0,43168.0,43082.0,43729.0,44196.0,both
1336,Michigan,Washtenaw County,346042,347807,344767,347563,344791.0,349048.0,351213.0,354289.0,357029.0,358880.0,both
45,Alabama,Madison County,307509,313796,320914,327744,334811.0,339574.0,342696.0,346720.0,350112.0,353089.0,both
462,Georgia,Glynn County,73447,74753,76044,76820,79626.0,80215.0,80985.0,81592.0,82343.0,83579.0,both
2674,Texas,Hemphill County,3321,3307,3410,3463,3807.0,3957.0,4069.0,4121.0,4163.0,4264.0,both
1203,Maine,Hancock County,53225,53374,53371,53447,54418.0,54546.0,54548.0,54800.0,54738.0,54659.0,both
1679,Montana,Valley County,6877,6874,6889,6771,7369.0,7476.0,7497.0,7627.0,7624.0,7659.0,both
1997,North Carolina,Perquimans County,12098,12446,12772,12734,13453.0,13461.0,13536.0,13590.0,13462.0,13440.0,both
2291,Pennsylvania,Blair County,126008,125987,125923,126122,127089.0,127192.0,127015.0,126426.0,126016.0,125593.0,both
2752,Texas,Parker County,104690,108639,112054,114919,116927.0,118526.0,119790.0,120169.0,122565.0,126042.0,both
1796,New Hampshire,Belknap County,60885,61027,61276,61358,60088.0,60281.0,60422.0,60221.0,60428.0,60641.0,both
1561,Missouri,Johnson County,51687,52009,52161,52657,52595.0,53459.0,54465.0,54491.0,54410.0,53951.0,both
167,Arkansas,Perry County,10237,10362,10297,10312,10445.0,10394.0,10336.0,10340.0,10239.0,10189.0,both
65,Alabama,Washington County,17369,17124,17088,17069,17581.0,17336.0,17115.0,16869.0,16863.0,16804.0,both
2058,North Dakota,Nelson County,3266,3224,3171,3129,3126.0,3066.0,3082.0,3075.0,3042.0,2968.0,both
1308,Michigan,Mason County,28785,28633,28632,28637,28705.0,28651.0,28677.0,28659.0,28786.0,28783.0,both
1826,New Jersey,Union County,520285,519738,521816,526426,536499.0,540707.0,544840.0,549340.0,553049.0,555786.0,both
2210,Oklahoma,Lincoln County,32203,32217,32070,32199,34273.0,34321.0,34213.0,34316.0,34627.0,35042.0,both
2349,Pennsylvania,Westmoreland County,363645,363131,362627,362251,365169.0,364566.0,363252.0,361128.0,359353.0,357956.0,both

Checking that the state population was actually dropped:

In [179]:
Check2 = (CountyPopulations['STATE'] == CountyPopulations['COUNTY'])
Check2.value_counts()

False    3142
dtype: int64

In [180]:
CountyPopulations = CountyPopulations.drop('_merge', axis=1)
CountyPopulations

,STATE,COUNTY,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
1,Alabama,Autauga County,49105,49834,50354,50756,54571.0,55253.0,55175.0,55038.0,55290.0,55347.0
2,Alabama,Baldwin County,168516,172815,176212,179878,182265.0,186659.0,190396.0,195126.0,199713.0,203709.0
3,Alabama,Barbour County,29556,29736,29836,29737,27457.0,27226.0,27159.0,26973.0,26815.0,26489.0
4,Alabama,Bibb County,21285,21485,21589,21587,22915.0,22733.0,22642.0,22512.0,22549.0,22583.0
5,Alabama,Blount County,55978,56866,57794,58345,57322.0,57711.0,57776.0,57734.0,57658.0,57673.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3191,Wyoming,Sweetwater County,37948,39320,39942,41226,43806.0,44041.0,45104.0,45162.0,44925.0,44626.0
3192,Wyoming,Teton County,19666,20073,20541,20710,21294.0,21482.0,21697.0,22347.0,22905.0,23125.0
3193,Wyoming,Uinta County,19631,20071,20537,20927,21118.0,20912.0,20989.0,21022.0,20903.0,20822.0
3194,Wyoming,Washakie County,7671,7805,7807,7911,8533.0,8469.0,8443.0,8443.0,8316.0,8328.0
3195,Wyoming,Weston County,6568,6845,6928,7009,7208.0,7114.0,7065.0,7160.0,7185.0,7234.0

In [181]:
CountyPopulations = CountyPopulations.melt(id_vars=['STATE', 'COUNTY'])
CountyPopulations

         STATE             COUNTY variable     value
0      Alabama     Autauga County     2006   49105.0
1      Alabama     Baldwin County     2006  168516.0
2      Alabama     Barbour County     2006   29556.0
3      Alabama        Bibb County     2006   21285.0
4      Alabama      Blount County     2006   55978.0
...        ...                ...      ...       ...
31415  Wyoming  Sweetwater County     2015   44626.0
31416  Wyoming       Teton County     2015   23125.0
31417  Wyoming       Uinta County     2015   20822.0
31418  Wyoming    Washakie County     2015    8328.0
31419  Wyoming      Weston County     2015    7234.0

[31420 rows x 4 columns]

In [182]:
CountyPopulations.rename({'STATE': 'State', 'COUNTY': 'County', 'variable': 'Year', 'value': 'Population'}, axis=1, inplace=True)
CountyPopulations

         State             County  Year  Population
0      Alabama     Autauga County  2006     49105.0
1      Alabama     Baldwin County  2006    168516.0
2      Alabama     Barbour County  2006     29556.0
3      Alabama        Bibb County  2006     21285.0
4      Alabama      Blount County  2006     55978.0
...        ...                ...   ...         ...
31415  Wyoming  Sweetwater County  2015     44626.0
31416  Wyoming       Teton County  2015     23125.0
31417  Wyoming       Uinta County  2015     20822.0
31418  Wyoming    Washakie County  2015      8328.0
31419  Wyoming      Weston County  2015      7234.0

[31420 rows x 4 columns]

In [193]:
CountyPopulations.to_csv('CountyPopulations.csv')